sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.5

script: ./script/cibuild

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler # caching bundler gem packages will speed up build